=== AshuLara/lisa/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (depend?,header,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT depend EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event (handler*)>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|file|file_arch|raw)*>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT raw (#PCDATA)>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED>

<!ATTLIST depend
require CDATA #IMPLIED
conflict CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED >

<!ATTLIST event
fun CDATA #REQUIRED>

<!ATTLIST handler
fun CDATA #REQUIRED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED>

=== AshuLara/lisa/conf/modules/airspeed_ets.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Airspeed ETS module (I2C)
     @define AIRSPEED_ETS_SCALE scale factor (default 1.8)
     @define AIRSPEED_ETS_OFFSET offset (default 0)
     @define AIRSPEED_ETS_I2C_DEV i2c device (default i2c0)
     @define USE_AIRSPEED to use the data for airspeed control loop
     @define SENSOR_SYNC_SEND to transmit the data as it is acquired
     -->

<module name="airspeed_ets" dir="sensors">

  <header>
    <file name="airspeed_ets.h"/>
  </header>
  <init fun="airspeed_ets_init()"/>
  <periodic fun="airspeed_ets_read_periodic()" freq="10."/>
  <event fun="AirspeedEtsEvent()"/>

  <makefile>
    <file name="airspeed_ets.c"/>
  </makefile>

</module>

=== AshuLara/lisa/conf/modules/baro_ms5611_i2c.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Measurement Specialties MS5611-01BA pressure sensor (I2C)
     @param MS5611_I2C_DEV i2c device (default i2c0)
     -->

<module name="baro_ms5611_i2c" dir="sensors">
  <header>
    <file name="baro_ms5611_i2c.h"/>
  </header>
  <init fun="baro_ms5611_init()"/>
  <periodic fun="baro_ms5611_periodic()" freq="4" delay="0"/>
  <periodic fun="baro_ms5611_d1()" freq="4" delay="1"/>
  <periodic fun="baro_ms5611_d2()" freq="4" delay="2"/>
  <event fun="baro_ms5611_event()"/>
  <makefile target="ap">
    <file name="baro_ms5611_i2c.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/temp_temod.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Hygrosens TEMOD-I2C-Rx temperature sensor
     @define SCP_I2C_DEV i2c device (default i2c0)
     @define TEMOD_TYPE device type (default TEMOD_I2C_R1)
     -->

<module name="temp_temod" dir="meteo">
  <header>
    <file name="temp_temod.h"/>
  </header>
  <init fun="temod_init()"/>
  <periodic fun="temod_periodic()" freq="8"/>
  <event fun="temod_event()"/>
  <makefile target="ap">
    <file name="temp_temod.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/ins_xsens_MTiG_fixedwing.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="ins">
  <!-- <depend conflict="ins" -->
  <!-- <depend require="gps_xsens" -->
  <header>
    <file name="ins_module.h"/>
  </header>
  <init fun="ins_init()"/>
  <periodic fun="ins_periodic_task()" freq="60"/>
  <event fun="InsEventCheckAndHandle(handle_ins_msg())"/>
  <makefile>
    <define name="AHRS_TYPE_H" value="\\\"modules/ins/ins_xsens.h\\\"" />
    <define name="INS_MODULE_H" value="\\\"modules/ins/ins_xsens.h\\\"" />
    <define name="USE_UART$(XSENS_UART_NR)"/>
    <define name="INS_LINK" value="Uart$(XSENS_UART_NR)"/>
    <define name="UART$(XSENS_UART_NR)_BAUD" value="B230400"/>
    <define name="USE_GPS_XSENS"/>
    <define name="USE_GPS_XSENS_RAW_DATA" />
    <define name="GPS_NB_CHANNELS" value="16" />
    <define name="XSENS_OUTPUT_MODE" value="0x1836" />
    <file name="ins_xsens.c"/>
    <define name="AHRS_TRIGGERED_ATTITUDE_LOOP" />
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/sonar_maxbotix_booz.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Maxbotix Sonar driver
     @configure ADC_SONAR on which ADC the sensor is connected

     On Booz board, ADC_0 should be use by default (payload connector)
     -->

<module name="sonar">
  <header>
    <file name="sonar_maxbotix.h"/>
    <file name="../../subsystems/ins.h"/>
  </header>
  <init fun="maxbotix_init()"/>
  <periodic fun="maxbotix_read()" freq="10"/>
  <event fun="SonarEvent(ins_update_sonar)"/>
  <makefile>
    <file name="sonar_maxbotix.c"/>
  </makefile>
  <makefile target="ap">
    <define name="ADC_CHANNEL_SONAR" value="$(ADC_SONAR)"/>
    <define name="USE_$(ADC_SONAR)"/>
    <define name="USE_SONAR"/>
  </makefile>

</module>

=== AshuLara/lisa/conf/modules/airspeed_adc.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Airspeed ADC module
     @configure ADC_AIRSPEED on which ADC the sensor is connected
     @define AIRSPEED_SCALE/AIRSPEED_QUADRATIC_SCALE scale factor, quadratic is used if defined
     @define AIRSPEED_BIAS offset on ADC
     -->

<module name="airspeed_adc" dir="sensors">

  <header>
    <file name="airspeed_adc.h"/>
  </header>
  <init fun="airspeed_adc_init()"/>
  <periodic fun="airspeed_adc_update()" freq="10."/>

  <makefile>
    <file name="airspeed_adc.c"/>
  </makefile>
  <makefile target="ap">
    <define name="ADC_CHANNEL_AIRSPEED" value="$(ADC_AIRSPEED)"/>
    <define name="USE_$(ADC_AIRSPEED)"/>
  </makefile>

</module>

=== AshuLara/lisa/conf/modules/cam_roll.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="cam_roll" dir="cam_control">
  <header>
    <file name="cam.h"/>
  </header>
  <init fun="cam_init()"/>
  <periodic fun="cam_periodic()" freq="10."/>
  <makefile>
    <define name="MOBILE_CAM"/>
    <file name="cam_roll.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/booz_cam.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="booz_cam" dir="cam_control">
  <!-- depend require="booz_pwm|led" -->
  <header>
    <file name="booz_cam.h"/>
  </header>
  <init fun="booz_cam_init()"/>
  <periodic fun="booz_cam_periodic()" freq="10."/>
  <makefile>
    <define name="USE_CAM"/>
    <file name="booz_cam.c"/>
  </makefile>
</module>
