=== AshuLara/lisa/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (depend?,header,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT depend EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event (handler*)>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|file|file_arch|raw)*>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT raw (#PCDATA)>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED>

<!ATTLIST depend
require CDATA #IMPLIED
conflict CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED >

<!ATTLIST event
fun CDATA #REQUIRED>

<!ATTLIST handler
fun CDATA #REQUIRED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED>

=== AshuLara/lisa/conf/modules/ir_mlx.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="ir_mlx" dir="meteo">
  <header>
    <file name="ir_mlx.h"/>
  </header>
  <init fun="ir_mlx_init()"/>
  <periodic fun="ir_mlx_periodic()" freq="8"/>
  <event fun="ir_mlx_event()"/>
  <makefile target="ap">
    <file name="ir_mlx.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/generic_com.xml
<!DOCTYPE module SYSTEM "module.dtd">
<!-- Generic Com Module -->
<!-- Can be redefined :
     GENERIC_COM_I2C_DEV (default: i2c0)
     GENERIC_COM_SLAVE_ADDR (default: ??)
     -->

<module name="generic_com" dir="com">
  <header>
    <file name="generic_com.h"/>
  </header>
  <init fun="generic_com_init()"/>
  <periodic fun="generic_com_periodic()" period="180" start="start_com()" stop="stop_com()" autorun="TRUE"/>
  <event fun="generic_com_event()"/>
  <makefile>
    <file name="generic_com.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/max11040.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="max11040" dir="adcs">
  <header>
    <file name="max11040.h"/>
  </header>
  <init fun="max11040_init()"/>
  <periodic fun="max11040_periodic()" freq="4"/>
  <makefile>
    <file_arch name="max11040_hw.c"/>
    <file name="max11040.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/baro_bmp.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Bosch BMP085 pressure sensor
     @define BMP_I2C_DEV i2c device (default i2c0)
     @define SENSOR_SYNC_SEND to transmit the data as it is acquired
     -->

<module name="baro_bmp" dir="sensors">
  <header>
    <file name="baro_bmp.h"/>
  </header>
  <init fun="baro_bmp_init()"/>
  <periodic fun="baro_bmp_periodic()" freq="8"/>
  <event fun="baro_bmp_event()"/>
  <makefile target="ap">
    <file name="baro_bmp.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/gsm.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="gsm">
  <header>
    <file name="gsm.h"/>
  </header>
  <init fun="gsm_init()"/>
  <periodic fun="gsm_init_report()" period="60." delay="3599" autorun="TRUE"/>
  <periodic fun="gsm_send_report()" period="60." autorun="FALSE"/>
  <event fun="gsm_event()"/>
  <makefile>
    <file name="gsm.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/baro_ets.xml
<!DOCTYPE module SYSTEM "module.dtd">

<!--
     Baro ETS module (I2C)
     @define BARO_ETS_I2C_DEV i2c device (default i2c0)
     -->

<module name="baro_ets" dir="sensors">

  <header>
    <file name="baro_ets.h"/>
  </header>
  <init fun="baro_ets_init()"/>
  <periodic fun="baro_ets_read_periodic()" freq="10."/>
  <event fun="BaroEtsEvent()"/>

  <makefile>
    <file name="baro_ets.c"/>
  </makefile>

</module>

=== AshuLara/lisa/conf/modules/booz_drop.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="drop">
  <!-- depend require="booz_pwm" -->
  <header>
    <file name="booz_drop.h"/>
  </header>
  <init fun="booz_drop_init()"/>
  <periodic fun="booz_drop_periodic()" freq="10."/>
  <makefile>
    <define name="USE_DROP"/>
    <define name="DROP_SERVO_OPEN" value="2120"/>
    <define name="DROP_SERVO_CLOSED" value="1060"/>
    <file name="booz_drop.c"/>
  </makefile>
</module>

=== AshuLara/lisa/conf/modules/infrared_adc.xml
<!DOCTYPE module SYSTEM "module.dtd">
<!-- @define IR_ADC_READ_ONLY for read only module -->

<module name="ir_adc" dir="sensors">
  <header>
    <file name="infrared_adc.h"/>
  </header>
  <init fun="infrared_adc_init()"/>
  <periodic fun="infrared_adc_update()" freq="60."/>
  <makefile>
    <define name="USE_INFRARED_TELEMETRY"/>
    <file name="infrared.c" dir="subsystems/sensors"/>
    <file name="infrared_adc.c" dir="subsystems/sensors"/>
  </makefile>
  <makefile target="ap">
    <define name="ADC_CHANNEL_IR1" value="$(ADC_IR1)"/>
    <define name="ADC_CHANNEL_IR2" value="$(ADC_IR2)"/>
    <define name="ADC_CHANNEL_IR_TOP" value="$(ADC_IR_TOP)"/>
    <define name="USE_$(ADC_IR1)"/>
    <define name="USE_$(ADC_IR2)"/>
    <define name="USE_$(ADC_IR_TOP)"/>
  </makefile>
  <makefile target="sim">
    <file_arch name="sim_ir.c" dir="."/>
  </makefile>
</module>
